mkdir -p /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes

scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/dataCards/Majorana/UL2016post-2016pre-2017-2018/default-lowMassSRloose/tau/$1/shapes/cutbased/MaxOneTau.txt /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/shapes/datacard.txt

scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/A-EEE-Mu-searchregion.shapes.root   /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch1.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/C-TauEE-searchregion.shapes.root    /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch10.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/B-TauEE-searchregion.shapes.root    /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch11.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/D-TauEE-searchregion.shapes.root    /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch12.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/A-TauEMu-searchregion.shapes.root   /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch13.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/B-TauEMu-searchregion.shapes.root   /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch14.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/A-TauMuMu-searchregion.shapes.root  /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch15.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/C-TauMuMu-searchregion.shapes.root  /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch16.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/B-TauMuMu-searchregion.shapes.root  /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch17.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/D-TauMuMu-searchregion.shapes.root  /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch18.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/C-EEE-Mu-searchregion.shapes.root   /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch2.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/B-EEE-Mu-searchregion.shapes.root   /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch3.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/D-EEE-Mu-searchregion.shapes.root   /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch4.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/A-MuMuMu-E-searchregion.shapes.root /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch5.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/C-MuMuMu-E-searchregion.shapes.root /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch6.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/B-MuMuMu-E-searchregion.shapes.root /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch7.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/D-MuMuMu-E-searchregion.shapes.root /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch8.root
scp /storage_mnt/storage/user/lwezenbe/private/PhD/Analysis_CMSSW_10_2_22/CMSSW_10_2_22/src/HNL/Stat/data/shapes/default-lowMassSRloose/UL2016post-2016pre-2017-2018/tau/$1/Majorana/A-TauEE-searchregion.shapes.root    /user/lwezenbe/public_html/HNL/Stat/output/ForJas/lowMass/tau/$1/shapes/ch9.root

